spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
            - id: changgou_goods_route
              #              uri: http://localhost:18081
              uri: lb://goods
              predicates:
                #                - Host=cloud.changgou.com**
                #                - Path=/brand/**
              - Path=/api/brand**
              filters:
                #                - PrefixPath=/brand
              - StripPrefix=1
              - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的facatory
                args:
                  key-resolver: "#{@ipKeyResolver}"
                  redis-rate-limiter.replenishRate: 1
                  redis-rate-limiter.burstCapacity: 1
            - id: changgou_user_route
              #              uri: http://localhost:18081
              uri: lb://user
              predicates:
                #                - Host=cloud.changgou.com**
                #                - Path=/brand/**
              - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
              filters:
              - StripPrefix=1
            - id: changgou_order_route
                #              uri: http://localhost:18081
              uri: lb://order
              predicates:
                  #                - Host=cloud.changgou.com**
                  #                - Path=/brand/**
              - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**
              filters:
              - StripPrefix=1
  redis:
    host: 192.168.211.132
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true